services:
  app_proxy:
    environment:
      APP_HOST: dashboard
      APP_PORT: 8501

  engine:
    image: ghcr.io/naexuis/bch-rental-engine:0.1.7
    environment:
      BCH_CONFIG_DIR: /config
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/state:/root/bch_rental_engine/state
      - ${APP_DATA_DIR}/logs:/root/bch_rental_engine/logs

  dashboard:
    image: ghcr.io/naexuis/bch-rental-engine:0.1.7
    environment:
      BCH_CONFIG_DIR: /config
    command:
      - streamlit
      - run
      - dashboard/app.py
      - --server.port=8501
      - --server.address=0.0.0.0
    restart: unless-stopped
    depends_on:
      - engine
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/state:/root/bch_rental_engine/state